# Generated by Django 5.2.7 on 2025-10-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.CharField(default='', max_length=100, primary_key='True', serialize=False)),
                ('aluno_nome', models.CharField(default='', max_length=150)),
                ('aluno_CPF', models.CharField(default='', max_length=14)),
                ('aluno_data_nascimento', models.CharField(default='')),
            ],
        ),
    ]
