# Generated by Django 5.2.7 on 2025-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aluno_data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
